.MODEL SMALL
.STACK 100H
.DATA
;LODSB: SOURCE -> MEMORY (ARRAY/STRING) (1-DS:SI WILL BE USED TO HOLD THE OFFSET ADDRESS OF STRING/ARRAY)
        ;DESTINATION -> 2-REGISTER(AL)
STR1 DB "YZ$"

.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX

    ;REQUIREMENTS FOR LODSB
    LEA SI,STR1
    CLD ;DF=0
    LODSB
    ;DATA FROM [SI] TO AL
    ;THE VALUE OF SI WILL BE INCREMENTED
    MOV DL,AL
    MOV AH,02  ; DISPLAY THE SINGLE CHARACTER ON THE SCREEN
    INT 21H

    MOV AH,4CH
    INT 21H
MAIN ENDP
END MAIN
